version: '3.7'
networks:
  toolkit:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=toolkit'
      - 'MYSQL_PASSWORD=toolkit'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=toolkit'
      - 'TZ=Asia/Shanghai'
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - toolkit
  redis:
    container_name: redis
    image: 'redis:latest'
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /usr/local/redis/conf/redis.conf:/var/lib/redis/conf/redis.conf
      - /usr/local/redis/data:/data
    environment:
      - REDIS_PASSWORD=toolkit
      - ALLOW_EMPTY_PASSWORD=no
    networks:
      - toolkit