networks:
  toolkit:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=toolkit'
      - 'MYSQL_PASSWORD=toolkit'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=toolkit'
      - 'TZ=Asia/Shanghai'
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - toolkit
