spring:
  datasource:
    username: root
    password: chsqc578480
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toolkit?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKey: LTAI5tEJMyW8bRA4jgSmZvPi
  accessSecret: 7LJoIutd0RHnd8HutnHWwrtmkUubDZ
  bucketName: phenomenal-toolkit